apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: <your-registry-url>/tamar-nidam-artifacts/tamarnidam-webapp:latest
          ports:
            - containerPort: 8080:8080
          # env:
          #   - name: ENV_VARIABLE_NAME
          #     value: ENV_VARIABLE_VALUE
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: shared-data
              mountPath: /data
      tolerations:
      - key: "webapp"
        operator: "Equal"
        value: "mywebapp"
        effect: "NoExecute"
      volumes:
        - name: shared-data
          emptyDir: {}
